import {
  type AgentManifest,
  AgentManifestSchema,
} from "@/lib/agents/contract";
import type { SampleRole } from "@/lib/samples/roles";

export type ToolSkeletonInput = {
  slug: string;
  name: string;
  description: string;
  capabilities?: string[];
  sampleRoles?: SampleRole[];
  instrumentType?: "sample" | "synth" | "hybrid" | "effect";
};

export type ToolSkeletonInstance = {
  manifest: AgentManifest;
  files: Map<string, string>;
};

export function createToolSkeleton(
  input: ToolSkeletonInput,
): ToolSkeletonInstance {
  const instrument = resolveSkeletonInstrument(input.instrumentType ?? "sample");
  const manifest = AgentManifestSchema.parse({
    name: input.name,
    slug: input.slug,
    level: 1,
    origin: "generated",
    description: input.description,
    route: `/tools/${input.slug}`,
    instrument,
    capabilities: input.capabilities ?? ["generatePattern", "play", "recordOutput"],
    inputs: {
      samples: input.sampleRoles ?? ["loop", "oneshot", "melodic", "pad", "fx"],
      bpm: true,
      globalBpm: true,
      globalKey: true,
      scaleSearch: true,
      prompt: true,
      requiredAnalysis: ["global.true_peak_dbfs", "rhythm.onsets_s", "envelope.attack_ms", "slices"],
    },
    musicContext: {
      globalBpm: true,
      globalKey: true,
      scaleSearch: true,
    },
    outputs: { pattern: true, synthScene: false, audio: true, recording: true },
    autonomy: "assist",
    status: "enabled",
  });
  const exportName = `${toCamelCase(input.slug)}Manifest`;
  const files = new Map<string, string>([
    [`app/tools/${input.slug}/manifest.ts`, renderManifest(manifest, exportName)],
    [`app/tools/${input.slug}/page.tsx`, renderPage(input.slug, input.name)],
    [`app/tools/${input.slug}/client.tsx`, renderClient(input.slug, input.name, input.description)],
    [`app/tools/${input.slug}/lib/prompt.ts`, renderPrompt(input.slug, input.name, input.description)],
    [`app/tools/${input.slug}/__tests__/manifest.test.ts`, renderManifestTest(exportName)],
    [`app/tools/${input.slug}/client.test.tsx`, renderClientTest(input.slug, input.name)],
    [`app/tools/${input.slug}/lib/prompt.test.ts`, renderPromptTest(input.slug)],
  ]);

  return { manifest, files };
}

function resolveSkeletonInstrument(type: NonNullable<ToolSkeletonInput["instrumentType"]>) {
  if (type !== "sample") {
    throw new Error(
      `The current L2 skeleton supports sample instruments only; requested ${type}`,
    );
  }

  return {
    type: "sample",
    workflow: "sample-pattern",
    document: "pattern",
    usesSamples: true,
    usesSynthesis: false,
  };
}

function renderManifest(manifest: AgentManifest, exportName: string) {
  return [
    `import type { AgentManifest } from "@/lib/agents/contract";`,
    "",
    `export const ${exportName} = ${JSON.stringify(manifest, null, 2)} satisfies AgentManifest;`,
    "",
  ].join("\n");
}

function renderPage(slug: string, name: string) {
  return [
    `import { ${toPascalCase(slug)}Client } from "@/app/tools/${slug}/client";`,
    "",
    `export default function ${toPascalCase(slug)}Page() {`,
    `  return <${toPascalCase(slug)}Client />;`,
    "}",
    "",
    `export const metadata = { title: "${escapeString(name)} | ai-daw-tools" };`,
    "",
  ].join("\n");
}

function renderClient(slug: string, name: string, description: string) {
  return [
    `"use client";`,
    "",
    "import Link from \"next/link\";",
    "import { useEffect, useMemo, useState } from \"react\";",
    "import { Loader2, Pause, Play, Sparkles } from \"lucide-react\";",
    "",
    "import { Button } from \"@/components/ui/button\";",
    "import { LlmGeneratingOverlay } from \"@/components/llm-generating-overlay\";",
    "import { AudioOutputRecorder } from \"@/components/audio-output-recorder\";",
    "import { PatternLiveTrace } from \"@/components/pattern-live-trace\";",
    "import { SamplePicker } from \"@/components/sample-picker\";",
    "import { playIntelligenceSamplerPattern, stopIntelligenceSamplerPattern } from \"@/app/tools/intelligence-sampler/lib/play\";",
    "import { readGenerateStream } from \"@/lib/ai/client-stream\";",
    "import type { GenerateStreamChunk } from \"@/lib/ai/contracts\";",
    "import { useGlobalMusicContextStore } from \"@/lib/music/use-global-music-context\";",
    "import { createPattern, createStep, createTrack, PatternSchema, type Pattern, type Track } from \"@/lib/pattern/schema\";",
    "import { getDefaultLibrarySample } from \"@/lib/samples/library\";",
    "",
    `const TOOL_SLUG = "${slug}";`,
    `const TOOL_NAME = "${escapeString(name)}";`,
    `const TOOL_DESCRIPTION = "${escapeString(description)}";`,
    "const TRACK_NAMES = [\"main\", \"repeat\", \"reverse\", \"fill\"] as const;",
    "const SAMPLE_ROLES = [\"loop\", \"oneshot\", \"melodic\", \"pad\", \"fx\"] as const;",
    "",
    `export function ${toPascalCase(slug)}Client() {`,
    "  const defaultSample = useMemo(() => getDefaultLibrarySample([...SAMPLE_ROLES]), []);",
    "  const [sampleId, setSampleId] = useState(defaultSample.id);",
    "  const [sampleName, setSampleName] = useState(defaultSample.name);",
    "  const [sampleRole, setSampleRole] = useState<Track[\"role\"]>(defaultSample.role);",
    "  const [sliceCount, setSliceCount] = useState(16);",
    "  const [pattern, setPattern] = useState(() =>",
    "    createGeneratedPattern(defaultSample.id, defaultSample.name, defaultSample.role),",
    "  );",
    "  const [prompt, setPrompt] = useState(\"stutter the source with gated repeats\");",
    "  const [streamText, setStreamText] = useState(\"\");",
    "  const [isPlaying, setIsPlaying] = useState(false);",
    "  const [isGenerating, setIsGenerating] = useState(false);",
    "  const [error, setError] = useState<string | null>(null);",
    "  const musicalContext = useGlobalMusicContextStore((state) => state.context);",
    "  const hydrateGlobalContext = useGlobalMusicContextStore((state) => state.hydrate);",
    "  const suggestions = useMemo(",
    "    () => [",
    "      \"tight vocal stutter with gated repeats\",",
    "      \"sparse off-grid chops with reverse fills\",",
    "      \"probability-heavy glitch loop that keeps the downbeat\",",
    "    ],",
    "    [],",
    "  );",
    "",
    "  useEffect(() => {",
    "    function handleGlobalContext(event: Event) {",
    "      const detail = (event as CustomEvent<typeof musicalContext>).detail;",
    "      setPattern((current) =>",
    "        current.bpm === detail.bpm",
    "          ? current",
    "          : PatternSchema.parse({ ...current, bpm: detail.bpm }),",
    "      );",
    "    }",
    "",
    "    window.addEventListener(\"global-music-context-change\", handleGlobalContext);",
    "    hydrateGlobalContext();",
    "    return () => {",
    "      window.removeEventListener(\"global-music-context-change\", handleGlobalContext);",
    "    };",
    "  }, [hydrateGlobalContext]);",
    "",
    "  function selectSample(sample: { id: string; name: string; role: Track[\"role\"] }) {",
    "    setSampleId(sample.id);",
    "    setSampleName(sample.name);",
    "    setSampleRole(sample.role);",
    "    setPattern((current) =>",
    "      PatternSchema.parse({",
    "        ...current,",
    "        metadata: {",
    "          ...current.metadata,",
    "          sourceSampleId: sample.id,",
    "          sourceSampleName: sample.name,",
    "        },",
    "        tracks: current.tracks.map((track) => ({",
    "          ...track,",
    "          sampleId: sample.id,",
    "          role: sample.role,",
    "        })),",
    "      }),",
    "    );",
    "  }",
    "",
    "  function toggleStep(trackId: string, stepIndex: number) {",
    "    setPattern((current) =>",
    "      PatternSchema.parse({",
    "        ...current,",
    "        tracks: current.tracks.map((track) =>",
    "          track.id === trackId",
    "            ? {",
    "                ...track,",
    "                steps: track.steps.map((step, index) =>",
    "                  index === stepIndex",
    "                    ? createStep({",
    "                        ...step,",
    "                        active: !step.active,",
    "                        slot: step.slot ?? track.slot ?? 0,",
    "                      })",
    "                    : step,",
    "                ),",
    "              }",
    "            : track,",
    "        ),",
    "      }),",
    "    );",
    "  }",
    "",
    "  function setTrackSlot(trackId: string, slot: number) {",
    "    setPattern((current) =>",
    "      PatternSchema.parse({",
    "        ...current,",
    "        tracks: current.tracks.map((track) =>",
    "          track.id === trackId",
    "            ? {",
    "                ...track,",
    "                slot,",
    "                steps: track.steps.map((step) => createStep({ ...step, slot })),",
    "              }",
    "            : track,",
    "        ),",
    "      }),",
    "    );",
    "  }",
    "",
    "  function setBpm(bpm: number) {",
    "    setPattern((current) => PatternSchema.parse({ ...current, bpm }));",
    "  }",
    "",
    "  function setSwing(swing: number) {",
    "    setPattern((current) => PatternSchema.parse({ ...current, swing }));",
    "  }",
    "",
    "  async function togglePlayback() {",
    "    if (isPlaying) {",
    "      await stopIntelligenceSamplerPattern();",
    "      setIsPlaying(false);",
    "      return;",
    "    }",
    "",
    "    await playIntelligenceSamplerPattern(pattern, { musicalContext, sliceCount });",
    "    setIsPlaying(true);",
    "  }",
    "",
    "  async function generatePattern() {",
    "    setIsGenerating(true);",
    "    setError(null);",
    "    setStreamText(\"\");",
    "",
    "    try {",
    "      const response = await fetch(\"/api/generate\", {",
    "        method: \"POST\",",
    "        headers: { \"Content-Type\": \"application/json\" },",
    "        body: JSON.stringify({",
    "          toolSlug: TOOL_SLUG,",
    "          mode: \"fresh\",",
    "          prompt,",
    "          context: {",
    "            pattern,",
    "            sampleId,",
    "            sampleName,",
    "            sampleRole,",
    "            bpm: pattern.bpm,",
    "            swing: pattern.swing,",
    "            musicalContext,",
    "            sliceCount,",
    "          },",
    "        }),",
    "      });",
    "",
    "      await readGenerateStream(response, handleChunk);",
    "    } catch (unknownError) {",
    "      setError(unknownError instanceof Error ? unknownError.message : \"Generation failed\");",
    "    } finally {",
    "      setIsGenerating(false);",
    "    }",
    "  }",
    "",
    "  function handleChunk(chunk: GenerateStreamChunk) {",
    "    if (chunk.type === \"partial\" || chunk.type === \"final\") {",
    "      const nextPattern = chunk.pattern;",
    "      setStreamText(JSON.stringify(nextPattern, null, 2));",
    "      const parsed = PatternSchema.safeParse(nextPattern);",
    "      if (parsed.success) {",
    "        setPattern(parsed.data);",
    "      }",
    "      return;",
    "    }",
    "",
    "    if (chunk.type === \"prompt\") {",
    "      setStreamText(chunk.prompt);",
    "      return;",
    "    }",
    "",
    "    if (chunk.type === \"error\") {",
    "      setError(chunk.message);",
    "    }",
    "  }",
    "",
    "  return (",
    "    <main className=\"min-h-screen bg-zinc-950 text-zinc-100\">",
    "      <section className=\"mx-auto flex max-w-7xl flex-col\">",
    "        <header className=\"flex flex-wrap items-center justify-between gap-3 border-b border-zinc-800 p-4\">",
    "          <div>",
    "            <Link href=\"/dashboard\" className=\"text-xs text-zinc-500 hover:text-cyan-200\">",
    "              /dashboard",
    "            </Link>",
    "            <h1 className=\"mt-1 text-lg text-zinc-100\">{TOOL_NAME}</h1>",
    "            <p className=\"mt-1 max-w-3xl text-xs text-zinc-500\">{TOOL_DESCRIPTION}</p>",
    "          </div>",
    "          <div className=\"flex items-center gap-2 text-xs text-zinc-500\">",
    "            <span>L1</span>",
    "            <span className=\"text-cyan-300\">generated</span>",
    "            <span>{sampleName}</span>",
    "          </div>",
    "        </header>",
    "",
    "        <div className=\"flex flex-wrap items-center gap-3 border-b border-zinc-800 p-4\">",
    "          <SamplePicker",
    "            id={`${TOOL_SLUG}-sample`}",
    "            label=\"source\"",
    "            value={sampleId}",
    "            roles={SAMPLE_ROLES}",
    "            onSelect={selectSample}",
    "          />",
    "          <label className=\"flex items-center gap-2 text-xs text-zinc-500\">",
    "            bpm",
    "            <input",
    "              className=\"h-9 w-20 rounded-sm border border-zinc-700 bg-zinc-950 px-2 text-zinc-100\"",
    "              type=\"number\"",
    "              min={40}",
    "              max={260}",
    "              value={pattern.bpm}",
    "              onChange={(event) => setBpm(Number(event.target.value))}",
    "            />",
    "          </label>",
    "          <label className=\"flex items-center gap-2 text-xs text-zinc-500\">",
    "            swing",
    "            <input",
    "              className=\"w-32 accent-cyan-300\"",
    "              type=\"range\"",
    "              min={0}",
    "              max={0.5}",
    "              step={0.01}",
    "              value={pattern.swing}",
    "              onChange={(event) => setSwing(Number(event.target.value))}",
    "            />",
    "          </label>",
    "          <label className=\"flex items-center gap-2 text-xs text-zinc-500\">",
    "            slices",
    "            <select",
    "              className=\"h-9 rounded-sm border border-zinc-700 bg-zinc-950 px-2 text-zinc-100\"",
    "              value={sliceCount}",
    "              onChange={(event) => setSliceCount(Number(event.target.value))}",
    "            >",
    "              {[8, 16, 32].map((count) => (",
    "                <option key={count} value={count}>",
    "                  {count}",
    "                </option>",
    "              ))}",
    "            </select>",
    "          </label>",
    "          <Button variant={isPlaying ? \"danger\" : \"solid\"} onClick={() => void togglePlayback()}>",
    "            {isPlaying ? <Pause className=\"size-4\" /> : <Play className=\"size-4\" />}",
    "            {isPlaying ? \"stop\" : \"play\"}",
    "          </Button>",
    "          <Button disabled={isGenerating} onClick={() => void generatePattern()}>",
    "            {isGenerating ? <Loader2 className=\"size-4 animate-spin\" /> : <Sparkles className=\"size-4\" />}",
    "            generate",
    "          </Button>",
    "          <AudioOutputRecorder filename={TOOL_SLUG} />",
    "          <PatternLiveTrace patternId={pattern.id} />",
    "        </div>",
    "",
    "        <div className=\"grid border-b border-zinc-800 lg:grid-cols-[minmax(0,1fr)_360px]\">",
    "          <section className=\"overflow-x-auto p-4\">",
    "            <div className=\"min-w-[760px] space-y-2\">",
    "              {pattern.tracks.map((track) => (",
    "                <div key={track.id} className=\"grid grid-cols-[160px_1fr] items-center gap-3\">",
    "                  <div className=\"flex items-center gap-2\">",
    "                    <span className=\"w-20 truncate text-xs text-zinc-400\">{track.name}</span>",
    "                    <select",
    "                      aria-label={`${track.name} slice`}",
    "                      className=\"h-8 rounded-sm border border-zinc-800 bg-zinc-950 px-2 text-xs text-zinc-100\"",
    "                      value={track.slot ?? 0}",
    "                      onChange={(event) => setTrackSlot(track.id, Number(event.target.value))}",
    "                    >",
    "                      {Array.from({ length: sliceCount }, (_, slot) => (",
    "                        <option key={slot} value={slot}>",
    "                          s{slot + 1}",
    "                        </option>",
    "                      ))}",
    "                    </select>",
    "                  </div>",
    "                  <div",
    "                    className=\"grid gap-1\"",
    "                    style={{ gridTemplateColumns: \"repeat(16, minmax(0, 1fr))\" }}",
    "                  >",
    "                    {track.steps.map((step, stepIndex) => (",
    "                      <button",
    "                        className={step.active ? \"h-8 border border-cyan-300 bg-cyan-300 text-zinc-950\" : \"h-8 border border-zinc-800 bg-zinc-950 text-zinc-700 hover:bg-zinc-900\"}",
    "                        key={`${track.id}-${stepIndex}`}",
    "                        title={`${track.name} step ${stepIndex + 1}`}",
    "                        type=\"button\"",
    "                        onClick={() => toggleStep(track.id, stepIndex)}",
    "                      >",
    "                        {step.active ? \"x\" : \"\"}",
    "                      </button>",
    "                    ))}",
    "                  </div>",
    "                </div>",
    "              ))}",
    "            </div>",
    "          </section>",
    "",
    "          <aside className=\"relative overflow-hidden border-t border-zinc-800 p-4 lg:border-l lg:border-t-0\">",
    "            {isGenerating ? (",
    "              <LlmGeneratingOverlay",
    "                detail=\"Prompting the LLM for a generated tool pattern.\"",
    "                label=\"generating pattern\"",
    "              />",
    "            ) : null}",
    "",
    "            <label className=\"block text-xs text-zinc-500\">",
    "              generation prompt",
    "            <textarea",
    "              className=\"mt-2 h-28 w-full resize-none rounded-sm border border-zinc-700 bg-zinc-950 p-3 text-xs text-zinc-100 outline-none focus:border-cyan-300\"",
    "              value={prompt}",
    "              onChange={(event) => setPrompt(event.target.value)}",
    "            />",
    "            </label>",
    "            <div className=\"mt-3 grid gap-2\">",
    "              {suggestions.map((suggestion) => (",
    "                <button",
    "                  className=\"border border-zinc-800 px-3 py-2 text-left text-xs text-zinc-300 hover:border-cyan-300 hover:text-white\"",
    "                  key={suggestion}",
    "                  type=\"button\"",
    "                  onClick={() => setPrompt(suggestion)}",
    "                >",
    "                  {suggestion}",
    "                </button>",
    "              ))}",
    "            </div>",
    "            {error ? <p className=\"mt-3 text-xs text-red-300\">{error}</p> : null}",
    "            <pre className=\"mt-3 max-h-64 overflow-auto border border-zinc-800 bg-black p-3 text-[11px] leading-5 text-zinc-500\">",
    "              {streamText || pattern.metadata.rationale || \"AI prompt, rationale, or pattern JSON will appear here\"}",
    "            </pre>",
    "          </aside>",
    "        </div>",
    "      </section>",
    "    </main>",
    "  );",
    "}",
    "",
    "function createGeneratedPattern(sampleId: string, sampleName: string, role: Track[\"role\"]): Pattern {",
    "  return createPattern({",
    "    id: `${TOOL_SLUG}-pattern`,",
    "    name: `${TOOL_NAME} pattern`,",
    "    bpm: 138,",
    "    swing: 0.08,",
    "    bars: 1,",
    "    stepsPerBar: 16,",
    "    tracks: TRACK_NAMES.map((trackName, trackIndex) =>",
    "      createTrack({",
    "        id: trackName,",
    "        name: trackName,",
    "        sampleId,",
    "        role,",
    "        slot: trackIndex,",
    "        chokeGroup: `${TOOL_SLUG}-source`,",
    "        steps: Array.from({ length: 16 }, (_, stepIndex) =>",
    "          createStep({",
    "            active:",
    "              (trackIndex === 0 && stepIndex % 4 === 0) ||",
    "              (trackIndex === 1 && [3, 7, 11, 15].includes(stepIndex)) ||",
    "              (trackIndex === 2 && stepIndex === 10) ||",
    "              (trackIndex === 3 && stepIndex >= 12),",
    "            slot: trackIndex,",
    "            velocity: trackIndex === 1 ? 0.72 : 1,",
    "            probability: trackIndex === 3 ? 0.68 : 1,",
    "            microShift: trackIndex === 1 ? -0.06 : 0,",
    "            repeats: trackIndex === 1 ? 2 : 1,",
    "            reverse: trackIndex === 2,",
    "            decay: trackIndex === 0 ? 0.8 : 0.45,",
    "          }),",
    "        ),",
    "      }),",
    "    ),",
    "    metadata: {",
    "      toolSlug: TOOL_SLUG,",
    "      sourceSampleId: sampleId,",
    "      sourceSampleName: sampleName,",
    "      createdBy: \"manual\",",
    "      rationale: \"Generated instrument scaffold with uploadable source, slice mapping, and choke-aware stutter lanes.\",",
    "      tags: [\"generated\", \"stutter\"],",
    "    },",
    "  });",
    "}",
    "",
  ].join("\n");
}

function renderPrompt(slug: string, name: string, description: string) {
  return [
    `import type { AiSampleContext } from "@/lib/ai/sample-context";`,
    `import type { Pattern } from "@/lib/pattern/schema";`,
    "",
    `export function build${toPascalCase(slug)}SystemPrompt() {`,
    "  return [",
    `    "You are the ${escapeString(name)} L1 agent inside ai-daw-tools.",`,
    `    "${escapeString(description)}",`,
    `    "Return one valid Pattern JSON object only.",`,
    `    "Use pitchCents and tuningRef when the global scale/key should affect sample playback.",`,
    `    "Use metadata.rationale for visible decisions.",`,
    "  ].join(\"\\n\");",
    "}",
    "",
    `export function build${toPascalCase(slug)}Prompt({`,
    "  pattern,",
    "  sample,",
    "  vibe,",
    "}: {",
    "  pattern: Pattern;",
    "  sample: AiSampleContext;",
    "  vibe: string;",
    "}) {",
    "  return [",
    `    "tool: ${slug}",`,
    "    `sample: ${sample.name} (${sample.pack}, ${sample.role})`,",
    "    `vibe: ${vibe || \"make a musical generated pattern\"}`,",
    "    `current pattern: ${JSON.stringify(pattern)}`,",
    "    \"Preserve sample ids. Use tuningRef degrees for scale-aware steps and emit compact metadata.rationale.\",",
    "  ].join(\"\\n\");",
    "}",
    "",
  ].join("\n");
}

function renderManifestTest(exportName: string) {
  return [
    `import { describe, expect, it } from "vitest";`,
    `import { AgentManifestSchema } from "@/lib/agents/contract";`,
    `import { ${exportName} } from "../manifest";`,
    "",
    `describe("${exportName}", () => {`,
    "  it(\"matches the shared manifest schema\", () => {",
    `    expect(AgentManifestSchema.parse(${exportName})).toMatchObject({ level: 1 });`,
    "  });",
    "});",
    "",
  ].join("\n");
}

function renderClientTest(slug: string, name: string) {
  return [
    `import { render, screen } from "@testing-library/react";`,
    `import { describe, expect, it } from "vitest";`,
    "",
    `import { ${toPascalCase(slug)}Client } from "./client";`,
    "",
    `describe("${slug} client", () => {`,
    "  it(\"renders a usable generated instrument interface\", () => {",
    `    render(<${toPascalCase(slug)}Client />);`,
    "",
    `    expect(screen.getByText("${escapeString(name)}")).toBeInTheDocument();`,
    "    expect(screen.getByLabelText(\"source\")).toBeInTheDocument();",
    "    expect(screen.getByRole(\"button\", { name: /play/i })).toBeInTheDocument();",
    "    expect(screen.getByRole(\"button\", { name: /generate/i })).toBeInTheDocument();",
    "    expect(screen.getByTitle(\"main step 1\")).toBeInTheDocument();",
    "  });",
    "});",
    "",
  ].join("\n");
}

function renderPromptTest(slug: string) {
  return [
    `import { describe, expect, it } from "vitest";`,
    `import { createPattern, createTrack } from "@/lib/pattern/schema";`,
    `import { build${toPascalCase(slug)}Prompt, build${toPascalCase(slug)}SystemPrompt } from "./prompt";`,
    "",
    `describe("${slug} prompt", () => {`,
    "  it(\"builds non-empty prompt text\", () => {",
    "    const pattern = createPattern({",
    "      tracks: [createTrack({ id: \"track\", name: \"track\", sampleId: \"sample\" })],",
    "    });",
    `    expect(build${toPascalCase(slug)}SystemPrompt()).toContain("ai-daw-tools");`,
    `    expect(build${toPascalCase(slug)}Prompt({`,
    "      pattern,",
    "      sample: { id: \"sample\", name: \"Sample\", pack: \"test\", role: \"loop\" },",
    "      vibe: \"test vibe\",",
    "    })).toContain(\"test vibe\");",
    "  });",
    "});",
    "",
  ].join("\n");
}

function toCamelCase(value: string) {
  return value.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase());
}

function toPascalCase(value: string) {
  const camel = toCamelCase(value);
  return `${camel.charAt(0).toUpperCase()}${camel.slice(1)}`;
}

function escapeString(value: string) {
  return value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"");
}
