import {
  escapeString,
  toPascalCase,
} from "@/lib/agents/templates/tool-skeleton/shared";

export function renderHybridClient(slug: string, name: string, description: string) {
  return [
    `"use client";`,
    "",
    "import Link from \"next/link\";",
    "import { useEffect, useMemo, useState } from \"react\";",
    "import { Copy, Download, FileMusic, Loader2, Pause, Play, Sparkles } from \"lucide-react\";",
    "",
    "import { createDefaultSynthScene } from \"@/app/tools/evolving-fm-synth/lib/agent\";",
    "import { fetchSynthSceneFromGateway } from \"@/app/tools/evolving-fm-synth/lib/gateway-request\";",
    "import { getScaleDisplayName, SynthSceneSchema, type SynthScene } from \"@/app/tools/evolving-fm-synth/lib/schema\";",
    "import { playEvolvingFmSynthScene, stopEvolvingFmSynthScene } from \"@/app/tools/evolving-fm-synth/lib/tone-playback\";",
    "import { AudioOutputRecorder } from \"@/components/audio-output-recorder\";",
    "import { LlmGeneratingOverlay } from \"@/components/llm-generating-overlay\";",
    "import { SamplePicker } from \"@/components/sample-picker\";",
    "import { Button } from \"@/components/ui/button\";",
    "import { renderSynthSceneToWav } from \"@/lib/audio/synth-wav-render\";",
    "import { downloadSynthSceneMidi } from \"@/lib/midi/synth-scene\";",
    "import { useGlobalMusicContextStore } from \"@/lib/music/use-global-music-context\";",
    "import { getDefaultLibrarySample } from \"@/lib/samples/library\";",
    "import type { SampleRole } from \"@/lib/samples/roles\";",
    "import { usePromptParamState } from \"@/lib/tools/use-prompt-param\";",
    "",
    `const TOOL_SLUG = "${slug}";`,
    `const TOOL_NAME = "${escapeString(name)}";`,
    `const TOOL_DESCRIPTION = "${escapeString(description)}";`,
    "const SAMPLE_ROLES: SampleRole[] = [\"loop\", \"oneshot\", \"melodic\", \"pad\", \"fx\"];",
    "",
    `export function ${toPascalCase(slug)}Client() {`,
    "  const defaultSample = useMemo(() => getDefaultLibrarySample([...SAMPLE_ROLES]), []);",
    "  const [prompt, setPrompt] = usePromptParamState(TOOL_DESCRIPTION);",
    "  const [scene, setScene] = useState<SynthScene>(() => createDefaultSynthScene(TOOL_DESCRIPTION));",
    "  const [sample, setSample] = useState<{ id: string; name: string; role: string }>({",
    "    id: defaultSample.id,",
    "    name: defaultSample.name,",
    "    role: defaultSample.role,",
    "  });",
    "  const [isGenerating, setIsGenerating] = useState(false);",
    "  const [isRendering, setIsRendering] = useState(false);",
    "  const [isPlaying, setIsPlaying] = useState(false);",
    "  const [copiedJson, setCopiedJson] = useState(false);",
    "  const [agentStatus, setAgentStatus] = useState(\"sample-informed local patch ready\");",
    "  const [error, setError] = useState<string | null>(null);",
    "  const context = useGlobalMusicContextStore((state) => state.context);",
    "  const hydrateGlobalContext = useGlobalMusicContextStore((state) => state.hydrate);",
    "",
    "  useEffect(() => {",
    "    hydrateGlobalContext();",
    "    return () => {",
    "      void stopEvolvingFmSynthScene();",
    "    };",
    "  }, [hydrateGlobalContext]);",
    "",
    "  useEffect(() => {",
    "    setScene((current) =>",
    "      SynthSceneSchema.parse({",
    "        ...current,",
    "        bpm: context.bpm,",
    "        swing: context.swing,",
    "        key: context.key.tonic,",
    "        scale: context.key.scaleId,",
    "      }),",
    "    );",
    "  }, [context]);",
    "",
    "  async function togglePlayback() {",
    "    if (isPlaying) {",
    "      await stopEvolvingFmSynthScene();",
    "      setIsPlaying(false);",
    "      return;",
    "    }",
    "",
    "    await playEvolvingFmSynthScene(scene);",
    "    setIsPlaying(true);",
    "  }",
    "",
    "  async function generateScene() {",
    "    setIsGenerating(true);",
    "    setError(null);",
    "    setAgentStatus(\"gateway pending\");",
    "    try {",
    "      const result = await fetchSynthSceneFromGateway({",
    "        mode: \"generate\",",
    "        musicalContext: context,",
    "        prompt: buildHybridPrompt(prompt, sample),",
    "        scene,",
    "      });",
    "      setScene(result.scene);",
    "      setAgentStatus(result.warning ?? `${result.source} hybrid scene ready`);",
    "    } catch (unknownError) {",
    "      setError(unknownError instanceof Error ? unknownError.message : \"Hybrid generation failed\");",
    "      setAgentStatus(\"local patch kept\");",
    "    } finally {",
    "      setIsGenerating(false);",
    "    }",
    "  }",
    "",
    "  async function renderWav() {",
    "    setIsRendering(true);",
    "    try {",
    "      const blob = await renderSynthSceneToWav(scene);",
    "      const href = URL.createObjectURL(blob);",
    "      const anchor = document.createElement(\"a\");",
    "      anchor.href = href;",
    "      anchor.download = `${TOOL_SLUG}.wav`;",
    "      anchor.click();",
    "      URL.revokeObjectURL(href);",
    "    } finally {",
    "      setIsRendering(false);",
    "    }",
    "  }",
    "",
    "  async function copySceneJson() {",
    "    try {",
    "      await navigator.clipboard.writeText(JSON.stringify({ scene, sourceSample: sample }, null, 2));",
    "      setCopiedJson(true);",
    "      window.setTimeout(() => setCopiedJson(false), 1500);",
    "    } catch (unknownError) {",
    "      setError(unknownError instanceof Error ? unknownError.message : \"Clipboard copy failed\");",
    "    }",
    "  }",
    "",
    "  return (",
    "    <main className=\"min-h-screen bg-zinc-950 text-zinc-100\">",
    "      <section className=\"mx-auto flex max-w-7xl flex-col\">",
    "        <header className=\"flex flex-wrap items-center justify-between gap-3 border-b border-zinc-800 p-4\">",
    "          <div>",
    "            <Link href=\"/dashboard\" className=\"text-xs text-zinc-500 hover:text-zinc-200\">",
    "              /dashboard",
    "            </Link>",
    "            <h1 className=\"mt-1 text-lg text-zinc-100\">{TOOL_NAME}</h1>",
    "            <p className=\"mt-1 max-w-3xl text-xs text-zinc-500\">{TOOL_DESCRIPTION}</p>",
    "          </div>",
    "          <div className=\"flex items-center gap-2 text-xs text-zinc-500\">",
    "            <span>L1</span>",
    "            <span className=\"text-zinc-200\">generated hybrid</span>",
    "            <span>{scene.key} {getScaleDisplayName(scene.scale)}</span>",
    "            <span>{sample.name}</span>",
    "          </div>",
    "        </header>",
    "",
    "        <div className=\"relative grid border-b border-zinc-800 lg:grid-cols-[minmax(0,1fr)_360px]\">",
    "          {isGenerating ? (",
    "            <LlmGeneratingOverlay",
    "              detail=\"Prompting the LLM for a sample-informed SynthScene.\"",
    "              label=\"generating hybrid scene\"",
    "              tone=\"solid\"",
    "            />",
    "          ) : null}",
    "          <section className=\"p-4\">",
    "            <SamplePicker",
    "              id={`${TOOL_SLUG}-source`}",
    "              label=\"source sample\"",
    "              roles={SAMPLE_ROLES}",
    "              value={sample.id}",
    "              onSelect={(nextSample) => setSample({ id: nextSample.id, name: nextSample.name, role: nextSample.role })}",
    "            />",
    "            <label className=\"mt-3 block text-xs text-zinc-500\">",
    "              hybrid prompt",
    "              <textarea",
    "                className=\"mt-2 h-28 w-full resize-none rounded-sm border border-zinc-700 bg-zinc-950 p-3 text-xs text-zinc-100 outline-none focus:border-zinc-200\"",
    "                value={prompt}",
    "                onChange={(event) => setPrompt(event.target.value)}",
    "              />",
    "            </label>",
    "            <div className=\"mt-3 flex flex-wrap gap-2\">",
    "              <Button variant={isPlaying ? \"danger\" : \"solid\"} onClick={() => void togglePlayback()}>",
    "                {isPlaying ? <Pause className=\"size-4\" /> : <Play className=\"size-4\" />}",
    "                {isPlaying ? \"stop\" : \"play\"}",
    "              </Button>",
    "              <Button disabled={isGenerating} onClick={() => void generateScene()}>",
    "                {isGenerating ? <Loader2 className=\"size-4 animate-spin\" /> : <Sparkles className=\"size-4\" />}",
    "                generate",
    "              </Button>",
    "              <Button disabled={isRendering} onClick={() => void renderWav()}>",
    "                <Download className=\"size-4\" />",
    "                {isRendering ? \"rendering\" : \"download wav\"}",
    "              </Button>",
    "              <Button onClick={() => downloadSynthSceneMidi(scene, `${TOOL_SLUG}.mid`)}>",
    "                <FileMusic className=\"size-4\" />",
    "                download midi",
    "              </Button>",
    "              <AudioOutputRecorder filename={TOOL_SLUG} sourceId={TOOL_SLUG} />",
    "              <Button onClick={() => void copySceneJson()}>",
    "                <Copy className=\"size-4\" />",
    "                {copiedJson ? \"copied\" : \"copy json\"}",
    "              </Button>",
    "            </div>",
    "            <div className=\"mt-3 text-xs text-zinc-500\">agent {agentStatus}</div>",
    "            {error ? <p className=\"mt-3 text-xs text-red-300\">{error}</p> : null}",
    "          </section>",
    "",
    "          <aside className=\"border-t border-zinc-800 p-4 text-xs leading-5 text-zinc-500 lg:border-l lg:border-t-0\">",
    "            <div className=\"text-zinc-300\">sample-informed boundary</div>",
    "            <p className=\"mt-2\">This generated hybrid template uses the source sample as prompt context and emits a SynthScene. It does not claim full resynthesis or dual-document routing.</p>",
    "            <pre className=\"mt-3 max-h-52 overflow-auto border border-zinc-800 bg-black p-3 text-[11px]\">",
    "              {JSON.stringify({ sourceSample: sample, scene: { bpm: scene.bpm, key: scene.key, scale: scene.scale, voices: scene.voices.length } }, null, 2)}",
    "            </pre>",
    "          </aside>",
    "        </div>",
    "      </section>",
    "    </main>",
    "  );",
    "}",
    "",
    "function buildHybridPrompt(prompt: string, sample: { id: string; name: string; role: string }) {",
    "  return [",
    "    prompt,",
    "    `source sample: ${sample.name} (${sample.role}, ${sample.id})`,",
    "    \"Use the sample as timbral and rhythmic reference. Emit a playable SynthScene, not a fake resynthesis artifact.\",",
    "  ].join(\"\\n\");",
    "}",
    "",
  ].join("\n");
}
