import type { AgentManifest } from "@/lib/agents/contract";

export const drumMachineManifest: AgentManifest = {
  name: "drum machine",
  slug: "drum-machine",
  level: 1,
  origin: "installed",
  description: "Circular Euclidean drum timelines with prompt-mapped geometry.",
  route: "/tools/drum-machine",
  instrument: {
    type: "sample",
    workflow: "drum-machine",
    document: "pattern",
    usesSamples: true,
    usesSynthesis: false,
  },
  capabilities: [
    "sequence",
    "mutatePattern",
    "polyrhythm",
    "euclideanRhythm",
    "circularGeometry",
    "promptToMath",
    "fxSlots",
    "recordOutput",
  ],
  inputs: {
    samples: ["break", "loop", "oneshot", "fx"],
    bpm: true,
    globalBpm: true,
    globalKey: true,
    scaleSearch: true,
    prompt: true,
    description: false,
    referenceAgent: false,
    audioSources: [],
    requiredAnalysis: ["global.true_peak_dbfs", "rhythm.onsets_s", "envelope.attack_ms", "slices"],
  },
  musicContext: {
    globalBpm: true,
    globalKey: true,
    scaleSearch: true,
  },
  outputs: {
    pattern: true,
    synthScene: false,
    midi: false,
    visualScene: false,
    audio: true,
    recording: true,
    files: false,
    manifest: false,
  },
  exports: {
    document: "pattern",
    audio: {
      strategy: "offline-render",
      formats: ["wav"],
      maxDefaultDurationSec: 120,
      requiresUserGestureForPreview: true,
    },
  },
  fx: {
    enabled: true,
  },
  autonomy: "assist",
  status: "enabled",
};
