import { describe, expect, it } from "vitest";

import {
  encodeMidiFile,
  sanitizeMidiFilename,
  type MidiExportInput,
} from "@/lib/midi/export";

describe("MIDI export framework", () => {
  it("encodes a deterministic Standard MIDI File with tempo and note events", () => {
    const input: MidiExportInput = {
      bpm: 120,
      name: "Test Clip",
      notes: [
        { midi: 60, startBeat: 0, durationBeats: 1, velocity: 0.5 },
        {
          channel: 1,
          midi: 64,
          pitchBendCents: 25,
          startBeat: 1,
          durationBeats: 0.5,
          velocity: 0.8,
        },
      ],
      textEvents: ["generated by test"],
    };

    const first = encodeMidiFile(input);
    const second = encodeMidiFile(input);
    const text = String.fromCharCode(...first);

    expect(first).toEqual(second);
    expect(text).toContain("MThd");
    expect(text).toContain("MTrk");
    expect(text).toContain("Test Clip");
    expect(Array.from(first.slice(8, 14))).toEqual([0, 0, 0, 1, 1, 224]);
    expect(Array.from(first)).toEqual(
      expect.arrayContaining([0xff, 0x51, 0x03, 0x07, 0xa1, 0x20]),
    );
    expect(Array.from(first)).toEqual(
      expect.arrayContaining([0x90, 60, 64, 0x80, 60, 0]),
    );
    expect(Array.from(first)).toEqual(expect.arrayContaining([0xe1]));
    expect(Array.from(first.slice(-4))).toEqual([0x00, 0xff, 0x2f, 0x00]);
  });

  it("sanitizes MIDI filenames for browser downloads", () => {
    expect(sanitizeMidiFilename("Deep Pad.mid")).toBe("deep-pad.mid");
    expect(sanitizeMidiFilename("  Weird / Clip Name  ")).toBe(
      "weird-clip-name.mid",
    );
    expect(sanitizeMidiFilename("")).toBe("export.mid");
  });
});
