import type { AgentManifest } from "@/lib/agents/contract";

export const cameraThereminManifest = {
  name: "Camera Theremin",
  slug: "camera-theremin",
  level: 1,
  origin: "installed",
  description:
    "Prompt-selectable camera synth that quantizes hand, gesture, face, eye, or body motion into the selected key and scale.",
  route: "/tools/camera-theremin",
  instrument: {
    type: "synth",
    workflow: "camera-theremin",
    document: "synth-scene",
    usesSamples: false,
    usesSynthesis: true,
  },
  capabilities: [
    "cameraTracking",
    "handLandmarks",
    "gestureTracking",
    "faceLandmarks",
    "eyeTracking",
    "poseLandmarks",
    "scaleQuantizedPitch",
    "continuousSynth",
    "fxSlots",
    "recordOutput",
  ],
  inputs: {
    samples: [],
    bpm: true,
    globalBpm: true,
    globalKey: true,
    scaleSearch: true,
    prompt: true,
    description: false,
    referenceAgent: false,
    audioSources: [],
    requiredAnalysis: [],
  },
  musicContext: {
    globalBpm: true,
    globalKey: true,
    scaleSearch: true,
  },
  outputs: {
    pattern: false,
    synthScene: true,
    midi: false,
    visualScene: false,
    audio: true,
    recording: true,
    files: false,
    manifest: false,
  },
  exports: {
    document: "synth-scene",
    audio: {
      strategy: "live-recording",
      formats: ["wav"],
      maxDefaultDurationSec: 120,
      requiresUserGestureForPreview: true,
    },
  },
  fx: {
    enabled: true,
  },
  autonomy: "manual",
  status: "enabled",
} satisfies AgentManifest;
